#ifndef ENCRIP_DESENCRIP_GLOBAL_H
#define ENCRIP_DESENCRIP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENCRIP_DESENCRIP_LIBRARY)
#  define ENCRIP_DESENCRIP_EXPORT Q_DECL_EXPORT
#else
#  define ENCRIP_DESENCRIP_EXPORT Q_DECL_IMPORT
#endif

#endif // ENCRIP_DESENCRIP_GLOBAL_H
